enable access to local Docker images from inside Dojo container

diff --git a/image/Dockerfile b/image/Dockerfile
--- a/image/Dockerfile
+++ b/image/Dockerfile
@@ -21,7 +21,29 @@ RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repos
   rm -r /tmp/dojo_git
 ############
 
+# Docker Installation (Package - Needs to be a version)
+ENV DOCKER_VERSION 19.03.13
+RUN set -eux; \
+  	if ! wget -O docker.tgz "https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz"; then \
+		echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from stable for x86_64"; \
+		exit 1; \
+	fi; \
+  	\
+	tar --extract \
+		--file docker.tgz \
+		--strip-components 1 \
+		--directory /usr/local/bin/ \
+	; \
+	rm docker.tgz; \
+	\
+	dockerd --version; \
+	docker --version
+# RUN apk add --no-cache docker
+
 #TODO: Add the tools the project needs
+
+# Make
+RUN apk add --no-cache make
 
 # Hadolint - https://github.com/hadolint/hadolint
 RUN wget -O /tmp/hadolint https://github.com/hadolint/hadolint/releases/download/${HADOLINT_VERSION}/hadolint-Linux-x86_64 \
